#!/bin/bash

# Cloudflare R2 Setup Script for VVU Scheduler
# This script helps you set up R2 storage integration

echo "================================================"
echo "  Cloudflare R2 Setup for VVU Scheduler"
echo "================================================"
echo ""

# Check if we're in the right directory
if [ ! -f "app.py" ] || [ ! -d "web" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    echo "   Expected: /Applications/XAMPP/xamppfiles/htdocs/vvu-scheduler"
    exit 1
fi

echo "✓ Project directory confirmed"
echo ""

# Step 1: Check Composer
echo "Step 1: Checking for Composer..."
if ! command -v composer &> /dev/null; then
    echo "⚠️  Composer not found!"
    echo ""
    echo "Install Composer first:"
    echo "  macOS: brew install composer"
    echo "  Or visit: https://getcomposer.org/download/"
    echo ""
    read -p "Press Enter after installing Composer, or Ctrl+C to exit..."
fi

echo "✓ Composer is available"
echo ""

# Step 2: Install AWS SDK
echo "Step 2: Installing AWS SDK for PHP (required for R2)..."
if [ -f "composer.json" ]; then
    composer require aws/aws-sdk-php
else
    # Create minimal composer.json if it doesn't exist
    echo '{
    "require": {
        "aws/aws-sdk-php": "^3.0"
    }
}' > composer.json
    composer install
fi

if [ $? -eq 0 ]; then
    echo "✓ AWS SDK installed successfully"
else
    echo "❌ Failed to install AWS SDK"
    exit 1
fi
echo ""

# Step 3: Gather R2 credentials
echo "Step 3: R2 Configuration"
echo ""
echo "You'll need the following from Cloudflare R2 Dashboard:"
echo "  1. Account ID"
echo "  2. Access Key ID"
echo "  3. Secret Access Key"
echo "  4. Bucket Name"
echo ""
echo "Get these from: https://dash.cloudflare.com > R2 > Manage R2 API Tokens"
echo ""

read -p "Do you want to configure R2 now? (y/n): " configure_now

if [ "$configure_now" = "y" ] || [ "$configure_now" = "Y" ]; then
    echo ""
    read -p "Enter your Cloudflare Account ID: " account_id
    read -p "Enter your R2 Access Key ID: " access_key
    read -sp "Enter your R2 Secret Access Key: " secret_key
    echo ""
    read -p "Enter your R2 Bucket Name [vvu-scheduler]: " bucket_name
    bucket_name=${bucket_name:-vvu-scheduler}
    
    # Construct endpoint
    endpoint="https://${account_id}.r2.cloudflarestorage.com"
    
    echo ""
    echo "Configuration Summary:"
    echo "  Account ID: $account_id"
    echo "  Access Key ID: $access_key"
    echo "  Bucket: $bucket_name"
    echo "  Endpoint: $endpoint"
    echo ""
    
    read -p "Save these credentials? (y/n): " save_creds
    
    if [ "$save_creds" = "y" ] || [ "$save_creds" = "Y" ]; then
        # Update config file
        cat > config/r2_config.php << EOF
<?php
/**
 * Cloudflare R2 Storage Configuration
 * 
 * Generated by setup script on $(date)
 */

return [
    'enabled' => true,
    'account_id' => '$account_id',
    'access_key_id' => '$access_key',
    'secret_access_key' => '$secret_key',
    'bucket' => '$bucket_name',
    'endpoint' => '$endpoint',
    'public_url' => null,
    'fallback_to_local' => true,
    'local_path' => __DIR__ . '/../csv/',
    'paths' => [
        'general' => 'csv/general/',
        'department' => 'csv/department/',
        'final' => 'csv/final/',
        'raw' => 'csv/raw/',
    ]
];
EOF
        
        echo "✓ Configuration saved to config/r2_config.php"
        echo ""
        echo "⚠️  IMPORTANT SECURITY NOTE:"
        echo "   Your credentials are now in config/r2_config.php"
        echo "   Make sure this file is in .gitignore to prevent exposing credentials!"
        echo ""
        
        # Check if .gitignore exists and has config entry
        if [ -f ".gitignore" ]; then
            if ! grep -q "config/r2_config.php" .gitignore; then
                echo "config/r2_config.php" >> .gitignore
                echo "✓ Added config/r2_config.php to .gitignore"
            fi
        else
            echo "config/r2_config.php" > .gitignore
            echo "✓ Created .gitignore with config entry"
        fi
    else
        echo "Configuration not saved. Edit config/r2_config.php manually."
    fi
else
    echo ""
    echo "Skipping configuration. Edit config/r2_config.php manually when ready."
fi

echo ""
echo "================================================"
echo "  Setup Complete!"
echo "================================================"
echo ""
echo "Next Steps:"
echo "  1. Verify your R2 bucket exists in Cloudflare Dashboard"
echo "  2. Test the integration by uploading a PDF in the scheduler"
echo "  3. Check the output message for 'Uploaded to R2' confirmation"
echo ""
echo "To disable R2 and use local storage:"
echo "  Edit config/r2_config.php and set 'enabled' => false"
echo ""
echo "For detailed documentation, see: R2_SETUP_GUIDE.md"
echo ""
