<?php
/**
 * Bulk Export for All Departments
 * 
 * Exports schedule data across all departments in various formats:
 * - CSV (by department)
 * - PDF (comprehensive report)
 * - Excel (formatted with colors and charts)
 * - Generates department-specific schedules
 */

ini_set('display_errors', 0);
header('Content-Type: application/json');
require_once 'db.php';
require_once 'error_handler.php';
require_once __DIR__ . '/../../lib/B2Storage.php';

/**
 * Get all departments
 */
function get_all_departments() {
    global $conn;
    
    if (!$conn->query("SHOW TABLES LIKE 'departments'")->num_rows) {
        // If no departments table, infer from courses
        $query = "SELECT DISTINCT department FROM courses ORDER BY department";
    } else {
        $query = "SELECT department_id, department_name FROM departments ORDER BY department_name";
    }
    
    $result = $conn->query($query);
    $departments = [];
    
    while ($row = $result->fetch_assoc()) {
        $departments[] = $row;
    }
    
    return $departments;
}

/**
 * Get department schedule
 */
function get_department_schedule($department) {
    global $conn;
    
    $schedule = [];
    
    // Try loading from B2 final_web_schedule.csv first
    $b2 = new B2Storage();
    $result = $b2->download('csv/final/final_web_schedule.csv');
    
    if ($result['success']) {
        $lines = explode("\n", $result['content']);
        $headers = str_getcsv(array_shift($lines));
        
        foreach ($lines as $line) {
            if (trim($line) === '') continue;
            $row = str_getcsv($line);
            $course = array_combine($headers, $row);
            
            if (($course['department'] ?? '') === $department || 
                ($course['course_code'] && strpos($course['course_code'], strtoupper(substr($department, 0, 3))) === 0)) {
                $schedule[] = $course;
            }
        }
    }
    
    return $schedule;
}

/**
 * Export department schedule to CSV
 */
function export_department_csv($department) {
    $schedule = get_department_schedule($department);
    
    if (empty($schedule)) {
        return null;
    }
    
    $output = fopen('php://memory', 'r+');
    
    // Headers
    $headers = array_keys($schedule[0]);
    fputcsv($output, $headers, ',', '"', '\\');
    
    // Rows
    foreach ($schedule as $row) {
        fputcsv($output, $row, ',', '"', '\\');
    }
    
    rewind($output);
    $csv_content = stream_get_contents($output);
    fclose($output);
    
    return $csv_content;
}

/**
 * Create CSV summary report
 */
function create_bulk_export_summary($format = 'csv') {
    global $conn;
    
    $departments = get_all_departments();
    $summary_data = [];
    
    foreach ($departments as $dept) {
        $dept_name = $dept['department_name'] ?? $dept['department'];
        $schedule = get_department_schedule($dept_name);
        
        $summary_data[] = [
            'department' => $dept_name,
            'courses_scheduled' => count($schedule),
            'export_date' => date('Y-m-d H:i:s'),
            'status' => 'ready'
        ];
    }
    
    return $summary_data;
}

/**
 * Generate Excel file using CSV format with structure
 */
function export_to_excel_format($departments = null) {
    global $conn;
    
    if (!$departments) {
        $dept_rows = get_all_departments();
        $departments = array_map(fn($d) => $d['department_name'] ?? $d['department'], $dept_rows);
    }
    
    // Create structured data suitable for Excel import
    $all_data = [];
    
    // Add metadata sheet
    $all_data['metadata'] = [
        ['Export Date', date('Y-m-d H:i:s')],
        ['Total Departments', count($departments)],
        ['Generated By', 'AI Scheduler'],
        []
    ];
    
    // Add department summaries
    $all_data['summary'] = [
        ['Department', 'Courses', 'Export Status']
    ];
    
    foreach ($departments as $dept) {
        $schedule = get_department_schedule($dept);
        $all_data['summary'][] = [
            $dept,
            count($schedule),
            'Exported'
        ];
    }
    
    // Add detailed schedules for each department
    foreach ($departments as $dept) {
        $schedule = get_department_schedule($dept);
        if (!empty($schedule)) {
            $all_data[$dept] = [array_keys($schedule[0])]; // Headers
            foreach ($schedule as $course) {
                $all_data[$dept][] = array_values($course);
            }
        }
    }
    
    return $all_data;
}

/**
 * Zip multiple exports
 */
function create_bulk_export_zip($departments = null) {
    global $conn;
    
    if (!$departments) {
        $dept_rows = get_all_departments();
        $departments = array_map(fn($d) => $d['department_name'] ?? $d['department'], $dept_rows);
    }
    
    $zip_path = '../../temp/bulk_export_' . date('YmdHis') . '.zip';
    $zip = new ZipArchive();
    
    if ($zip->open($zip_path, ZipArchive::CREATE) !== TRUE) {
        return ['success' => false, 'error' => 'Cannot create ZIP file'];
    }
    
    // Add summary
    $summary = create_bulk_export_summary('csv');
    $summary_csv = "Department,Courses Scheduled,Export Date,Status\n";
    foreach ($summary as $row) {
        $summary_csv .= implode(',', $row) . "\n";
    }
    $zip->addFromString('EXPORT_SUMMARY.csv', $summary_csv);
    
    // Add department schedules
    foreach ($departments as $dept) {
        $csv_content = export_department_csv($dept);
        if ($csv_content) {
            $filename = sanitize_filename($dept) . '.csv';
            $zip->addFromString($filename, $csv_content);
        }
    }
    
    // Add manifest
    $manifest = "AI Scheduler - Bulk Export\n";
    $manifest .= "Generated: " . date('Y-m-d H:i:s') . "\n";
    $manifest .= "Total Departments: " . count($departments) . "\n";
    $manifest .= "Departments Included:\n";
    foreach ($departments as $dept) {
        $manifest .= "  - " . $dept . "\n";
    }
    
    $zip->addFromString('MANIFEST.txt', $manifest);
    $zip->close();
    
    return [
        'success' => true,
        'zip_path' => $zip_path,
        'filename' => basename($zip_path),
        'departments_exported' => count($departments)
    ];
}

/**
 * Sanitize filename
 */
function sanitize_filename($filename) {
    $filename = preg_replace('/[^a-zA-Z0-9_-]/', '_', $filename);
    return substr($filename, 0, 100);
}

/**
 * Get export statistics
 */
function get_export_statistics() {
    global $conn;
    
    $departments = get_all_departments();
    $stats = [
        'total_departments' => count($departments),
        'total_courses' => 0,
        'total_sections' => 0,
        'department_breakdown' => []
    ];
    
    foreach ($departments as $dept) {
        $dept_name = $dept['department_name'] ?? $dept['department'];
        $schedule = get_department_schedule($dept_name);
        
        $stats['total_courses'] += count($schedule);
        $stats['department_breakdown'][] = [
            'department' => $dept_name,
            'courses' => count($schedule)
        ];
    }
    
    return $stats;
}

/**
 * API Endpoint
 */
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';
    
    if ($action === 'list_departments') {
        $departments = get_all_departments();
        echo json_encode([
            'success' => true,
            'departments' => $departments,
            'count' => count($departments)
        ]);
        
    } elseif ($action === 'export_department_csv' && isset($_POST['department'])) {
        $department = $_POST['department'];
        $csv_content = export_department_csv($department);
        
        if (!$csv_content) {
            http_response_code(404);
            echo json_encode(['success' => false, 'error' => 'No schedule found for department']);
            exit;
        }
        
        $filename = sanitize_filename($department) . '.csv';
        
        if (isset($_POST['download']) && $_POST['download'] === '1') {
            header('Content-Type: text/csv; charset=utf-8');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            echo $csv_content;
        } else {
            echo json_encode([
                'success' => true,
                'filename' => $filename,
                'content' => base64_encode($csv_content),
                'size' => strlen($csv_content)
            ]);
        }
        
    } elseif ($action === 'export_all_csv') {
        $departments_param = isset($_POST['departments']) ? 
            explode(',', $_POST['departments']) : null;
        
        $results = create_bulk_export_zip($departments_param);
        
        if ($results['success']) {
            echo json_encode([
                'success' => true,
                'message' => 'Export created successfully',
                'result' => $results
            ]);
        } else {
            http_response_code(500);
            echo json_encode($results);
        }
        
    } elseif ($action === 'export_summary') {
        $summary = create_bulk_export_summary('csv');
        echo json_encode([
            'success' => true,
            'summary' => $summary,
            'total_departments' => count($summary)
        ]);
        
    } elseif ($action === 'statistics') {
        $stats = get_export_statistics();
        echo json_encode([
            'success' => true,
            'statistics' => $stats
        ]);
        
    } else {
        http_response_code(400);
        echo json_encode(['error' => 'Unknown action']);
    }
    
} elseif ($_SERVER['REQUEST_METHOD'] === 'GET' && isset($_GET['action'])) {
    if ($_GET['action'] === 'download_zip' && isset($_GET['file'])) {
        $filename = basename($_GET['file']);
        $filepath = '../../temp/' . $filename;
        
        if (file_exists($filepath) && strpos($filepath, '../../temp/') === 0) {
            header('Content-Type: application/zip');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            header('Content-Length: ' . filesize($filepath));
            readfile($filepath);
        } else {
            http_response_code(404);
            echo 'File not found';
        }
    }
} else {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
}
?>
